### ISSUE TITLE
parse() returns naive timezone when tz is available

### ISSUE THREAD

**Issue by adamn** [scrapinghub/dateparser#179]
parse() ignores timezones by default.  It should maintain the timezone.

```python
>>> from dateutil.parser import parse
>>> parse('Wed, 11 May 2016 14:30:00 -0400')
datetime.datetime(2016, 5, 11, 14, 30, tzinfo=tzoffset(None, -14400))
>>> import dateparser
>>> dateparser.parse('Wed, 11 May 2016 14:30:00 -0400')
datetime.datetime(2016, 5, 11, 18, 30)
>>>
```

**Comment by adamn** [comment]
I know this is documented, but the current default timezone implementation doesn't seem parsimonious:

https://dateparser.readthedocs.io/en/latest/#settings

**Comment by waqasshabbir** [comment]
`parse()` converts timezone into `UTC` for the resultant `datetime` object unless specified otherwise. Think of this default choice as if you are collecting dates from a number of sources with different timezones, you'd want them all to be normalized in one timezone. Like you specified, it's configurable. You can achieve this in a couple ways. Either use `DateDataParser` like below or modify `settings` directly.

##### Using `DateDataParser`
```
In [1]: from dateparser.date import DateDataParser

In [2]: ddp = DateDataParser(settings={'RETURN_AS_TIMEZONE_AWARE': True, 'TIMEZONE': None})

In [4]: ddp.get_date_data('Wed, 11 May 2016 14:30:00 -0400')
Out[4]:
{'date_obj': datetime.datetime(2016, 5, 11, 14, 30, tzinfo=<StaticTzInfo 'UTC\-04:00'>),
 'period': u'day'}

In [5]: ddp.get_date_data('Wed, 11 May 2016 14:30:00 EST')
Out[5]:
{'date_obj': datetime.datetime(2016, 5, 11, 14, 30, tzinfo=<StaticTzInfo 'EST'>),
 'period': u'day'}

In [7]: ddp.get_date_data('Wed, 11 May 2016 14:30:00 EDT')
Out[7]:
{'date_obj': datetime.datetime(2016, 5, 11, 14, 30, tzinfo=<StaticTzInfo 'EDT'>),
 'period': u'day'}
```

##### Modifying `settings` directly
```
In [10]: from dateparser.conf import settings

In [11]: settings.TIMEZONE = None

In [12]: settings.RETURN_AS_TIMEZONE_AWARE = True

In [14]: from dateparser import parse

In [15]: parse('Wed, 11 May 2016, 15:30:00 PDT')
Out[15]: datetime.datetime(2016, 5, 11, 15, 30, tzinfo=<StaticTzInfo 'PDT'>)
```

**Comment by adamn** [comment]
My bad, I should have been more clear.  I'm suggesting that the default `RETURN_AS_TIMEZONE_AWARE` be changed from `False` to `True`.
