### ISSUE TITLE
guess or fix date feature?

### ISSUE THREAD

**Issue by eromoe** [scrapinghub/dateparser#203]
Hi, 
It is usually need clean all blank char from a text, then some date would be u'2016年6月2911:30', 
I think it is good to add a feature to detect broken date.

**Comment by waqasshabbir** [comment]
@eromoe dealing with poorly formatted dates become very challenging when you have to work with multiple natural languages which you have no proficiency at. I am not sure what's the best way to handle chinese dates for example, but since a native chinese speaker has better language context, she can handle this problem better. May be, you can implement something like that of your own on top of dateparser for Chinese and share it with us, we will add it to the `Recipes` section in docs. We don't have a `Recipe` section yet, it's just a thought.

**Comment by eromoe** [comment]
I write this to process date time.
```
ur'(?P<date>(?P<year>\d{4})(年|-|/|\.)(?P<month>\d{1,2})(月|-|/|\.)(?P<day>\d{1,2})(日)?)(?P<time>(?P<hour>\d{1,2})(时|:)?(?P<minute>\d{1,2})(分)?)?'
```

`year`  and `month` is usually exist,  according to (年|-|/|\.) and (月|-|/|\.), but day `(日)`,  hour `(时|:)` , minute `(分)` is not all always exist I think.

Why not create two template:

1. date order template( contain separator ),  like 

\1(year)\2(month)\3(day)\4(hour)\5(minute)

2. multiple natural languages word template, like
             year   month  day   hour   minute
Common:  -  -  None :  None
Chinese:  年 月 日?  (时|:)? 分?

Then just combine 1 and 2

**Comment by waqasshabbir** [comment]
@eromoe added corresponding simplification which fixes your example.
