### ISSUE TITLE
GSoC 2017 : Integrate unicode CLDR database with dateparser

### ISSUE THREAD

**Issue by sarthak5** [scrapinghub/dateparser#288]
I am a student of IIT Kharagpur, India and I want to contribute to dateparser in GSoC 2017. I went through the ideas page and found the idea of integrating unicode CLDR database interesting. CLDR data is available in XML and json formats. A [github repo](https://github.com/unicode-cldr) of CLDR data in json format is also maintained. 

Now integrating CLDR database can be done either by using yaml files for the data as currently used in dateparser or using json format as maintained in the CLDR repo. I think it should be better to use json files as it would lead to faster performance than using yaml. I am also thinking about adding support for calenders in CLDR database.

@waqasshabbir , @asadurski ,  could you guys tell me more what can be done with this project. It would be great to have some feedback from you guys before I write my proposal.

**Comment by waqasshabbir** [comment]
@sarthak5 appreciate your interest in dateparser. Thanks!

> Now integrating CLDR database can be done either by using yaml files for the data as currently used in dateparser or using json format as maintained in the CLDR repo. I think it should be better to use json files as it would lead to faster performance than using yaml. I am also thinking about adding support for calenders in CLDR database.

Without going too deep into the specifics, we like yaml for its rich feature set and its readability. Also, it has allowed us to retain language translations code in a very clean manner.

After having CLDR integration we expect dateparser to not only support all languages but also incorporate the locales bit of the information. For instance, standard date order for en-US is `mm-dd-yy` but for en-GB it is `dd-mm-yy`. This one will be an interesting one because as of now dateparser lacks the mechanism for defining locales. Also, some languages may only have one locale others multiple. Some may only differ in date order other also in parts of speech.

Plus, we also need to be mindful of how data from CLDR is going to be used with data we've with dateparser already which is very valuable and continues to be improved by the community.

P.S. You may want to attempt fixing this https://github.com/scrapinghub/dateparser/issues/253 it will help you get a neat idea of how dateparser defines and uses its language information.

**Comment by sarthak5** [comment]
@waqasshabbir , @asadurski , here is my draft of the proposal I am working on. Please provide some feedback so I can improve my proposal. 
[https://hackmd.io/s/H1LIB4hie](https://hackmd.io/s/H1LIB4hie)

**Comment by sarthak5** [comment]
@waqasshabbir @asadurski , [supplemental/territoryInfo.json](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/territoryInfo.json) in CLDR repo provides population data for territories and languages used. The data for language population is also listed [here](http://www.unicode.org/cldr/charts/31/supplemental/language_territory_information.html). It can be used to order the languages as per the total population that use the language.

**Comment by dipanm** [comment]
Good to see this in action.
