### ISSUE TITLE
Phrasing issues

### ISSUE THREAD

**Issue by giftig** [scrapinghub/dateparser#343]
I just had a very quick play with this and found some surprising inconsistencies.

```python
In [14]: parse('-30 days at midnight')
Out[14]: datetime.datetime(2017, 7, 18, 14, 39, 14, 370191)

In [15]: parse('-30 days at cucumber')  # To prove it's not simply ignoring midnight entirely

In [16]: parse('-30 days at midnight')
Out[16]: datetime.datetime(2017, 7, 18, 14, 39, 28, 320778)

In [17]: parse('midnight -30 days')
Out[17]: datetime.datetime(2017, 7, 18, 14, 39, 34, 138184)

In [18]: parse('midnight')
Out[18]: datetime.datetime(2017, 8, 17, 0, 0)

In [19]: parse('midnight + 1')
Out[19]: datetime.datetime(2017, 1, 17, 0, 0)

In [20]: parse('midnight + 1 day')
Out[20]: datetime.datetime(2017, 8, 16, 14, 39, 44, 962030)
```

looks like the library needs more work.

**Comment by redapple** [comment]
I have little experience with dateparser but I believe it's aimed at natural language dates, such as 
```
>>> import dateparser
>>> dateparser.parse('midnight')
datetime.datetime(2017, 8, 21, 0, 0)
>>> dateparser.parse('midnight tomorrow')
datetime.datetime(2017, 8, 22, 0, 0)
>>> dateparser.parse('midnight yesterday')
datetime.datetime(2017, 8, 20, 0, 0)
>>> dateparser.parse('midnight last week')
datetime.datetime(2017, 8, 14, 0, 0)
>>> dateparser.parse('midnight last month')
datetime.datetime(2017, 7, 21, 0, 0)
>>> dateparser.parse('midnight next week')
datetime.datetime(2017, 8, 28, 0, 0)
>>> dateparser.parse('midnight next month')
datetime.datetime(2017, 9, 21, 0, 0)
```

So I don't think it's expected to work with `+/- N days` strings (I may be wrong).

Though it does have issues with natural language input like these:
```
>>> dateparser.parse('midnight last monday')
>>> dateparser.parse('midnight next monday')
>>> dateparser.parse('midnight and one day')
datetime.datetime(2017, 8, 20, 0, 0)
```

> looks like the library needs more work.

Sure it does, and all contributions and reports are welcome. Thanks for reporting this one @giftig

**Comment by dipanm** [comment]
the correct usage is `"in 30 days [at]? <time>"` or `"30 days ago [at]? <time>"`
I think negative 'days' values shouldn't be accepted since -30 days ago sounds invalid from natural language issue. 

But then what exactly happens - to `'-30 days at midnight'`?
(reference file: freshness_date_parser.py)  

Basically, it does identify -30 days unit as a relative time 
So it takes primary reference `now` and tries add -30 days. But since neither `in` nor `ago` is present the operation fails - and somehow due to this, the component 'midnight' is no longer processed. what is returned is neither 30 days (added/subtracted) NOR does it apply 'midnigiht'.

To be sure: `'in -30 days at midnight'` does returns a date 30 days in advance (not behind) but puts current time. 
If you apply `"in 30 days at midnight"` actually returns both currect date and time as `"00:00"` time so -ve sign is what is affecting "midnight" part. 

However, according to me, if `in` and `out` are both missing or having -ve sign it should simply refuse to output which will be rather correct behaviour. 

In either case, if the input is invalid or vague it is always an open ended debate whether software should do best it can, or should out right reject.

**Comment by giftig** [comment]
Indeed, it'd be much better to fail than to produce confusing results. I only had a quick play around to get a feel for how it worked, but quickly ran into those scenarios where the parsing is failing. For my use case I ended up just implementing my own quite naive function to handle some specific formats I was interested in as there don't seem to be any libraries which provide the cases I was looking for.

> Sure it does, and all contributions and reports are welcome.
Just adding that my comment was not meant to be unconstructive, I was just pointing out that my snippet demonstrates a few inconsistencies which make it difficult to raise specific bugs without doing what dipanm did and diving into the code to diagnose case-by-case.

In my case I wanted to use the library so that semi-technical people could provide a date range like `--from 'now - 30d' --to 'now'` rather than having to manually figure out ISO timestamps, but I satisfied that simple requirement with ~30 lines instead. If the intention is solely for "natural" date parsing, I suspect it's not aimed at my use case anyway - and if that's the case I agree that negative figures should produce an error; something like "-7 days ago" isn't a natural way to specify a date imo.

**Comment by dipanm** [comment]
well  - if you interpret `in -30 days` as `30 days ago` - there is simpler way you can handle this with the dateparser. 

go to laungaugefile/en.yaml (or your language) . go to the last section called `simplifications:` and add a line at the bottom of it all, like:

`in -(\d+) days: \1 days ago`. 
this will convert every instance of in -30 days into 30days ago before processing. 

I tested this works! 
```
>>> 'in -30 days at midnight'
>>> 2017-07-24 00:00:00

```

**Comment by giftig** [comment]
Interesting. My requirements were quite specific and I noticed this library has a lot of dependencies so I opted for a much simpler / more naive solution regardless: https://gist.github.com/giftig/9e74658233384588037be3440a372c8b
