### ISSUE TITLE
Dateparser parses years as a date when STRICT_PARSING = True

### ISSUE THREAD

**Issue by wasabigeek** [scrapinghub/dateparser#356]
Dateparser with `STRICT_PARSING` parses a year wrongly: 
```
>>> dateparser.parse('2017', settings={'STRICT_PARSING': True})
datetime.datetime(2020, 1, 7, 0, 0)
```
I would have expected it to return `None` instead. Did I understand the docs wrongly?

For reference, the parsing seems ok without `STRICT_PARSING`:
```
>>> dateparser.parse('2017')
datetime.datetime(2017, 10, 30, 0, 0)
```

Setup:
- Python 3.5.2
- dateparser==0.6.0

**Comment by marcosmadr** [comment]
I investigated a bit this issue and I'm sharing what I've found so far.

Following there are two approaches to this problem:

1) Parsing a date with or without STRICT_PARSING parameter should use the same parser, and return the same result in order to keep consistency. After parsing the date/time string, we check for STRICT_PARSING parameter and return None if it's incomplete.

Currently, if the date is incomplete and STRICT_PARSING is set, it keeps trying to parse the data using other formats, so we end up with different results depending on if you are using STRICT_PARSING or not.

2) Other approach would be to not parse complete dates from 4 digits data. Parsing 4 digits as complete dates is generating quite weird results, for example:
>>> dateparser.parse('2001', settings={'STRICT_PARSING': True})
datetime.datetime(2000, 2, 1, 0, 0)
*MYD*
>>> dateparser.parse('2019', settings={'STRICT_PARSING': True})
datetime.datetime(2020, 1, 9, 0, 0)
*YMD*
>>> dateparser.parse('1983', settings={'STRICT_PARSING': True})
datetime.datetime(1983, 1, 9, 0, 0)
 *MDY*

Hey @asadurski , Could you give your opinion, if it's the right way to go?

**Comment by nherger** [comment]
I'm having the exact same issue. Ideally, I would expect None to be returned when executing something like this: 
`dateparser.parse('2011', settings={'STRICT_PARSING': True})`
Are there any updates on this?

**Comment by noviluni** [comment]
From my perspective, the `dateparser.parse()` method should do the best to return dates.

I know that `2017` doesn't seem a full date, but it theoretically fits for 2020-01-07.

I added a new PR separating the `no-spaces-time` parser from the `absolute-time` parser: https://github.com/scrapinghub/dateparser/pull/786

It would allow doing:

```python
from dateparser_data.settings import default_parsers

parsers = [parser for parser in default_parsers if parser != 'no-spaces-time']

dateparser.parse('2017', settings={'STRICT_PARSING': True, 'PARSERS': parsers})
```
(and it wouldn't return anything).

I know this doesn't fix the issue 100%, as you have to add specific settings, but in my opinion, we shouldn't change the default behavior, so we could consider this fixed when releasing that PR. Any strong opinion on this?

**Comment by noviluni** [comment]
Hi guys, we finally decided to exclude the `no-spaces-time` parser from the default parsers (PR: https://github.com/scrapinghub/dateparser/pull/786), so it will work as expected in the next version!
