### ISSUE TITLE
Test failure on some days

### ISSUE THREAD

**Issue by dotlambda** [scrapinghub/dateparser#440]
The line

https://github.com/scrapinghub/dateparser/blob/a01a4d2071a8f1d4b368543e5e09cde5eb880799/tests/test_search.py#L423

can lead to `ValueError: day is out of range for month` if `datetime.datetime.today().day > 30`.

I think all occurences of `datetime.datetime.today().*` in the tests should be replaced by something deterministic or by a random number in a suitabe range.

**Comment by rennerocha** [comment]
Inside the tests, there are 11 matches that calls `datetime.today()`. Most of them (10 matches) relates to parsing a single year string.

IMHO as the expected results are the returned date to have the day and month as today there is no need to change these scenarios as they will never fail (and we also guarantee that it will continue working as expected) in any day of the year.

The failing scenario happens because November doesn't have 31 days and the expected result in this case would be return the last day of the related month (if we execute `dateparse.parse('November')` and today is 31/Oct/2018, the result is 30/11/2018).

I think the best solution would be providing a scenario that will never fail (replacing November by October) instead of maintaining November and include some logic to define the value of the day that will be returned (as this logic should be tested elsewhere).
