### ISSUE TITLE
If pass empty string to dateparser.parse it tooks around 3-4 sec 

### ISSUE THREAD

**Issue by opensubb009** [scrapinghub/dateparser#470]
If we pass empty string to parse method, it takes around 3-4 seconds to process it.
It should have some validations checks into it.

```
import dateparser
import time
st = time.time()
date = dateparser.parse('')
ed = time.time()
print('Date::', date)
print('%2.3f sec' % (ed - st))
```
```
Output:
>> Date:: 
>> 3.434 sec
```

**Comment by lopuhin** [comment]
@opensubb009 thanks for reporting this. The speed should already be improved in master. Also the first call to ``parse`` might be a bit slower than the rest.

**Comment by flogrammer** [comment]
Hi,

I have also identified several ways to speed up the library (tailored to my needs). 

Firstly, if you only use "standard" Date formats and no relative formats - you can remove the FreshnessDateParser (date.py, line 185). The dateparser is just too powerful for my usecase, hence removing it lead to a 4times faster execution. 
Also my dateformats have not timestamp - removed line 182.

Now the parser is pretty fast, but still takes some time for invalid formats (such as your string - because all locales will be tested). That's why you might consider narrowing down to specific languages. If you already know that your date formats will only occur in 50 locales (instead of 200 locales) it will speed up the whole thing immensely.
Hope it helps =)

**Comment by noviluni** [comment]
Hi @opensubb009 @flogrammer, this was fixed in the last version. Now it should take less than 1 second to parse that string. On the other side, we implemented a new setting called `parsers` that allows selecting which parsers should be tested (as @flogrammer proposed) without editing the source code.

I will close this issue, feel free to re-open it if your problem persists.
