### ISSUE TITLE
"Feb 2011" parsing fails but Jan, Mar-Dec works

### ISSUE THREAD

**Issue by umrashrf** [scrapinghub/dateparser#49]
```
>>> from dateutil import parser
>>> parser.parse('Jan 2011', fuzzy=True)
datetime.datetime(2011, 1, 30, 0, 0)
>>> parser.parse('Feb 2011', fuzzy=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/umair/dev/venvs/nathanartz/local/lib/python2.7/site-packages/dateutil/parser.py", line 743, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/umair/dev/venvs/nathanartz/local/lib/python2.7/site-packages/dateutil/parser.py", line 310, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
>>> parser.parse('Dec 2011', fuzzy=True)
datetime.datetime(2011, 12, 30, 0, 0)
```

**Comment by umrashrf** [comment]
Most probably it's assuming 30 as day where Feb has only 28.

**Comment by umrashrf** [comment]
Ah it's a dateutil bug. Nevermind!

**Comment by umrashrf** [comment]
Ok apparently it's an issue with dateparser too.

```
>>> from dateparser.date import DateDataParser
>>> ddp = DateDataParser()
>>> ddp.get_date_data('Jan 2011')
{'date_obj': datetime.datetime(2011, 1, 30, 0, 0), 'period': 'day'}
>>> ddp.get_date_data('Feb 2011')
{'date_obj': None, 'period': 'day'}
>>> ddp.get_date_data('Mar 2011')
{'date_obj': datetime.datetime(2011, 3, 30, 0, 0), 'period': 'day'}
>>> ddp.get_date_data('Dec 2011')
{'date_obj': datetime.datetime(2011, 12, 30, 0, 0), 'period': 'day'}
```

**Comment by Allactaga** [comment]
Hi @umrashrf . Thank you for reporting this. Unfortunately we are relying on `dateutil` for parsing calendar-like dates, so if it could not parse it, we also can't.

I won't close this for now. If someone would like to contribute, here is an issue in `dateutil` repository: https://github.com/dateutil/dateutil/issues/25

**Comment by Allactaga** [comment]
Since recently we have copied part of `dateutil` code to our repo to have better control over the process. As it has appeared, the line that is responsible for the current issue also [ended up](https://github.com/scrapinghub/dateparser/blob/c0b7340bb7e4f670c876d5d3e8863ffe5afcf8db/dateparser/date_parser.py#L76) here, so now we are able to fix this issue on our side.

While working on this fix one should keep in mind that unlike solution proposed in `dateutil` repository we would want to *seamlessly* replace day if it exceeds days for the resulting month, but *ONLY* if it is valid date. What i mean is "Feb 30" and "June 32" should not be reduced to "Feb 28/June30", but considered to be not parseable and return `ValueError`

**Comment by Allactaga** [comment]
Resolved with https://github.com/scrapinghub/dateparser/pull/57
