### ISSUE TITLE
No option for PREFER_DATES_FROM for current day

### ISSUE THREAD

**Issue by charliesmart** [scrapinghub/dateparser#508]
It would be nice if there was an additional option to prefer the current date if available over the future or past one when parsing relative dates. This is primarily an issue when parsing dates in news articles, where the current date will be referred to only by the day of the week. 

For example, an article written on Friday, March 8 will use only the word "Friday" to describe March 8. But parsing 'Friday' with `'PREFER_DATES_FROM': 'future'` will return Friday, March 15 and  `'PREFER_DATES_FROM': 'past'` will return March 1.

Here's how I could imagine it working:

```python
>>> dateparser.parse('Friday', settings={
  'RELATIVE_BASE': datetime.datetime(2019, 3, 8),
  'PREFER_DATES_FROM':  'future',
  'PREFER_CURRENT_DATE': True
})
# Since RELATIVE_BASE is a Friday, returns RELATIVE_BASE
datetime.datetime(2019, 3, 8)
```

```python
>>> dateparser.parse('Friday', settings={
  'RELATIVE_BASE': datetime.datetime(2019, 3, 8),
  'PREFER_DATES_FROM':  'future',
  'PREFER_CURRENT_DATE': False
})

datetime.datetime(2019, 3, 15)
```

I can try to find some time to implement this if other people would find it useful.

**Comment by gypapp** [comment]
I haven't debugged it yet but at the first closer look the offending lines should be https://github.com/scrapinghub/dateparser/blob/master/dateparser/parser.py#L370-L371 and https://github.com/scrapinghub/dateparser/blob/master/dateparser/parser.py#L378-L379

If I am correct I may create PR to address this issue though I would prefer having a third option for `PREFER_DATES_FROM` instead of a separate option. By the way, the current
[docs suggest that](https://dateparser.readthedocs.io/en/latest/usage.html?highlight=current_period#handling-incomplete-dates):

> `PREFER_DATES_FROM` defaults to current_period and can have past and future as values.

or at least I interpreted it (ie. `current_period`) as if there were such an option.

**Comment by asadurski** [comment]
That is a real bug related only to weekdays. Parsing today's weekday name with default settings (current period) should return today's date, not last week.
What's more, we had some tests that supported that broken functionality. Thank you for voicing this, PR #559 is aimed at fix.
