### ISSUE TITLE
Day/month/year order for different locales

### ISSUE THREAD

**Issue by Allactaga** [scrapinghub/dateparser#52]
We should specify what day/month/year order is prefferable for different languages.
We can use [this information](http://en.wikipedia.org/wiki/Date_format_by_country) as a starting point and define `date_order = DMY` for each language in our file (don't forget to add a specific validation for this). Then, based on this info we should pass [proper arguments](https://labix.org/python-dateutil#head-b95ce2094d189a89f80f5ae52a05b4ab7b41af47) to dateutil parser.

**Comment by marven** [comment]
Will start working on this.

**Comment by alexis-via** [comment]
I am a new user of dateparser, and I was very disappointed to see that it doesn't take into account the language to guess the date format day/month/year vs month/day/year. For example:

```
>>> import dateparser
>>> dateparser.parse(u'2/12/2015', languages=['fr'])
datetime.datetime(2015, 2, 12, 0, 0)
```

In French, the day is always before the month, so the result should be datetime.datetime(2015, 12, 2, 0, 0). It's quite disappointing ; it means you ALWAYS have to give the date_formats as argument, otherwise you will have some big troubles !

**Comment by waqasshabbir** [comment]
Hi @alexis-via, we're working on adding preferred date order for different languages. See PR #73.

Also, can you please share more details on the error you reported [here](https://github.com/m3nu/invoice2data/issues/5). This can be a lot of help as on our end all tests are passing successfully.

Thank you.

**Comment by alexis-via** [comment]
@waqasshabbir OK, thanks for your answer !

About the problem I have that I reported on invoice2data, I am still trying to understand the exact issue and I'll report a bug if I confirm that the issue is in dateparser. I am in fact able to import dateparser from a python console (which contradics what I said on the github issue on invoice2data), but it never works from Odoo (odoo imports invoice2data which itself imports dateparser). It crashes on dateparser/conf.py on this line: https://github.com/scrapinghub/dateparser/blob/master/dateparser/conf.py#L44 and I don't understand why... it's like if get_data() wasn't doing anything. I'll try to get some help from senior python devs to have a better understanding of what happens and, if I confirm that it's dateparser fault and not odoo fault, I'll open a new bug report here.

**Comment by juliusdanek** [comment]
Has this been resolved?

**Comment by waqasshabbir** [comment]
Hi @juliusdanek not yet, it's a WIP. Should be resolved soon. Thanks!

**Comment by juliusdanek** [comment]
Awesome. Very excited! Love the package

2016-02-11 2:14 GMT-05:00 Waqas Shabir <notifications@github.com>:

**Comment by waqasshabbir** [comment]
`Locales` are a little tricky to add, so for now, we've associated date orders with languages and for english given the fact that UK/Australia english uses a different order than US, we rely on `settings.DATE_ORDER` default which is `MDY` and can be customized by supplying `settings` like below:

```
In [6]: parse('3-4-2015 06:00') 
Out[6]: datetime.datetime(2015, 3, 4, 6, 0)  # default - MDY

In [7]: parse('3-4-2015 06:00', settings={'DATE_ORDER': 'DMY'})
Out[7]: datetime.datetime(2015, 4, 3, 6, 0)
```
