### ISSUE TITLE
Parsing in YMD format

### ISSUE THREAD

**Issue by 4n4nd** [scrapinghub/dateparser#549]
dateparser.__version__ = '0.7.1'

Problematic code sequence:
```
import dateparser

print(dateparser.__version__)
print("my date = ", dateparser.parse("2019-08-02 11:51:09.138115"))

# This statement does nothing
dateparser.parse("2d")

print("my date = ", dateparser.parse("2019-08-02 11:51:09.138115"))
```
Code output:
```
0.7.1
my date =  2019-08-02 11:51:09.138115
my date =  2019-02-08 11:51:09.138115
```

Problem:
As you can see in the code output, the same date string gets parsed into two different formats, the first one being the correct one. This does not seem to happen when I remove `dateparser.parse("2d")` (line 7).

Current workaround:
To use `settings={"DATE_ORDER": "YMD"}` when parsing any date to force this format.

**Comment by rennerocha** [comment]
The first call uses `en` as locale (as none is specified). The second call (`dateparser.parse("2d")`) uses`es` as locale.

As `try_previous_locales=True`, in `DateDataParser` instance, and `es` is in `previous_locales` list (because of the second call), when we do the first call again, the string will be converted considering `es` as locale.

Lines of interest:
https://github.com/scrapinghub/dateparser/blob/master/dateparser/date.py#L303
https://github.com/scrapinghub/dateparser/blob/master/dateparser/date.py#L446

One option to avoid this side-effect would be set default as `False` for `DateDataParser.try_previous_locales`. This behaviour to try previous locales seems a bit magic to me, so IMO it would be better to explicitly enable if if we want and make clear in the docs that after that enabled, the results may vary between executions.

**Comment by 4n4nd** [comment]
Thanks

**Comment by epicfaace** [comment]
@rennerocha would you consider making `try_previous_locales` set to `False` by default in a new release (as a breaking change)? It's not clear that dateparser is nondeterministic and caused a quite difficult bug for me to trace, and it would make more sense for it to be deterministic by default (or clearly advertised as nondeterministic in the README).

**Comment by noviluni** [comment]
Hi @epicfaace 
It's not a problem to add a breaking change as we are working in a new, major, version. However, I think that this behavior (trying with previous locales) it's really important.

Imagine you are parsing a text that it's in Macedonian.

It will try with 131 different locales until it gets the correct locale and it will add it to the "previous locale list". Now imagine you have a list or a text with hundreds of dates to parse that are in Macedonian. It's clearly better to try directly with Macedonian instead of trying 131 different locales every time.

Snippet to reproduce it:

```python
import time

from dateparser.date import DateDataParser


max_times = 1000

p = DateDataParser(try_previous_locales=False)

start = time.time()
for _ in range(1, max_times):
    p.get_date_data("четврток")
end = time.time()

print("Without locale caching: {}".format(end - start))


p2 = DateDataParser(try_previous_locales=True)

start2 = time.time()
for _ in range(1, max_times):
    p2.get_date_data("четврток")
end2 = time.time()

print("With locale caching: {}".format(end2 - start2))
```

This is what I got:
```bash
Without locale caching: 10.915936708450317
With locale caching: 0.9248013496398926
```

There are other kinds of caching mechanisms when importing, but if you change the order (first trying with previously used locales and then without it) you will see a similar result: the result trying with previous locales is always faster than the other.


We could maybe disable it by default and add a section about performance tweaks, but I don't think it's a good idea as we have been trying to prioritize the best performance by default.

Any other idea / opinion?

**Comment by epicfaace** [comment]
@noviluni In my use case, I am using `dateparser` to parse dates from webpages, and I use snapshot tests to compare the parsed output from a given set of URLs. It's really important for me that a date parsing library is deterministic (at least that's what I expected), so it was just a surprise that by default it was not deterministic.

I see your point in that there's a tradeoff between being deterministic and prioritizing performance. In my opinion, most users of a date parsing library will already have an expectation that a library called "dateparser" is deterministic / has no side effects (because, as my intuition goes, "why would a date parsing function store state and be affected by what you've sent to it before?")

So I would suggest disabling it by default and adding a section about performance tweaks, as you mentioned.

In the end, it's up to you though, so if you decide not to do that, I would suggest that you at least include a prominent warning that "this library is not deterministic -- if you need it to be deterministic, set the `try_previous_locales` argument).

**Comment by epicfaace** [comment]
@noviluni I have an idea.

The code example you gave (creating an instance with `DateDataParser`) makes it clearer that calling `get_date_data` may store state -- because you're explicitly creating an instance. Perhaps in this case, it could make sense to set `try_previous_locales` to `True` -- since the user can always create a new instance of `DateDataParser` if they need to do so.

However, if I use `dateparser.parse` directly (which doesn't involve creating any instances of classes), it still makes the most sense to me for this function to be deterministic & without side effects, unlike the example above, since it's a single function and I can't create other instances of it.

**Comment by lopuhin** [comment]
+1 to change default to be deterministic, and document how enabling ``try_previous_locales`` can lead to non-determinism and how if affects perfromance. Re having different defaults in ``DateDataParser`` and ``dateparser.parse`` - I'm not sure, one drawback is that different defaults in different places can be surprising, and users which care about performance and do a lot of calls for one source would probably still read the docs and also try to narrow down the locales using external context.

**Comment by noviluni** [comment]
Ok, now that I hear your points of view I see it clearly and I think we can proceed with this!

@rennerocha do you have any WIP PR?

**Comment by noviluni** [comment]
Hey @4n4nd, @rennerocha, @epicfaace, @lopuhin!

I opened a new PR for handling this: https://github.com/scrapinghub/dateparser/pull/781 I would really appreciate your feedback.

(Note that it's not possible to reproduce the original error because of this change in the in `dateparser==0.7.4`: https://github.com/scrapinghub/dateparser/pull/625. However, you can find an equivalent issue here: https://github.com/scrapinghub/dateparser/issues/776)

Thanks!
