### ISSUE TITLE
GSOC 2020 - Number parser doubts

### ISSUE THREAD

**Issue by Avilad0** [scrapinghub/dateparser#652]

**Comment by Avilad0** [comment]
hello @noviluni  @kishan3 , I am still confused with what are all expectations out of the number parser project?

**Comment by noviluni** [comment]
Hi @Avilad0  

I think that all you need to know is here: http://gsoc2020.scrapinghub.com/ideas#number-parser  but, I will try to explain it better:

As you know, dateparser is used to parse localized dates. However, in these moments it doesn't support numbers written in natural language (examples: "Third of May" or "December twenty-eight"). What we want to do do is to be able to parse those numbers.
 
Note that basic support for numbers from 1 to 12 was added in the past: https://github.com/scrapinghub/dateparser/blob/master/dateparser_data/supplementary_language_data/date_translation_data/en.yaml but this is not enough, as it isn't useful to parse big numbers as years, or to parse ordinal numbers ("first", "second"...).

It's really important for the new implementation to be multilingual and to be really fast (performance is a must for this library). 

On the other side, it would be really good if the solution can be used by other projects (as price-parser: https://github.com/scrapinghub/price-parser), so we were thinking about creating a separated library.

Let me know if you have any doubt.

**Comment by Avilad0** [comment]
@noviluni, Thank you for the information.
Does only natural language have to support multiple languages or even the numbers should be in multiple languages when converted?

**Comment by Gallaecio** [comment]
I think converting natural language only to Arabic numbers should be fine. Being able to support alternative number systems could be cool, but I’m not sure if Dateparser (and price-parser) support non-arabic numbers at the moment.

**Comment by Avilad0** [comment]
Thank you @Gallaecio ..
can you tell me about how many different languages the organization is expecting to include in the Number Parser Project ?

**Comment by ShantanuDube** [comment]
> Thank you @Gallaecio ..
> can you tell me about how many different languages the organization is expecting to include in the Number Parser Project ?

same query

**Comment by Gallaecio** [comment]
The main goal would be to support internationalization; to design the implementation in a way that allows for people interesting in extending support to more languages to implement it, hopefully with only data files and no code changes, or with a defined and clear way to implement any required code changes.

As long as internationalization is in place, the number of supported languages would not be a problem. I would personally be happy if English and a second language are supported, because it would make it easier to understand how the internationalization is implemented.

Implementing support for any additional language as part of the project would be a welcome addition. But given a project presenting a good internationalization system but support only for English, and a project with support for as many languages as Dateparser supports but no easy way to extend support for additional languages, I personally would be inclined to go with the former :slightly_smiling_face:

**Comment by Avilad0** [comment]
Thanks 👍 ..
@Gallaecio  @noviluni  @kishan3 
I know it's pretty late but I have submitted my draft for review. It would be of immense help if any mentors can give some feedback and i make any necessary changes.
Also I have made a very small contribution which is not merged so will it affect my proposal if the contribution is very small?

**Comment by kishan3** [comment]
@Avilad0 Can you please share the link here?

**Comment by Avilad0** [comment]
https://docs.google.com/document/d/1grgfGE2FV7GABE57fq6TqLI8Y8_xPymSS-lCvae7Hb4/edit?usp=sharing
