### ISSUE TITLE
Even if I used 'STRICT_PARSING' True, it gives wrong results in partial date string

### ISSUE THREAD

**Issue by anoopparampil** [scrapinghub/dateparser#769]
```
> dateparser.parse(u'11:50', settings={'REQUIRE_PARTS': ['day', 'month', 'year'],'STRICT_PARSING': True})
 datetime.datetime(2050, 1, 1, 0, 0)

```
I have expected None. I don't want to parse if there is only time in the string
If we add a space in the starting of the string it gives None
`> dateparser.parse(u' 11:50', settings={'REQUIRE_PARTS': ['day', 'month', 'year'],'STRICT_PARSING': True})
`

**Comment by Gallaecio** [comment]
Interesting how 11:50 is interpreted as day 1 month 1 year 50.

**Comment by johntmyers** [comment]
Is this related?

https://github.com/scrapinghub/dateparser/issues/713

**Comment by Gallaecio** [comment]
Yes, they are indeed related. But we could keep both of them open, as in this case we are not talking about a regular number, but an hour interpreted as a date.

**Comment by noviluni** [comment]
This can be closed as it's fixed by this: https://github.com/scrapinghub/dateparser/pull/786

In the next version, this won't be returning a complete date. If you use it without settings it will parse the hours, and if you try to parse it with the settings you mentioned (either `REQUIRE_PARTS` or `STRICT_PARSING`) it will return `None`

```python
>>> dateparser.parse(u'11:50', settings={'STRICT_PARSING': True})
```
