### ISSUE TITLE
dateparser.parse('365 days') returns 364 days, while dateparser.parse('1 year') returns 365 days

### ISSUE THREAD

**Issue by dshefman1** [scrapinghub/dateparser#775]
dateparser.parse('365 days') returns 364 days, while dateparser.parse('1 year') returns 365 days

```
>>>print((datetime.now() - dateparser.parse('365 days')).days)
364
>>>print((datetime.now() - dateparser.parse('1 year')).days)
365
>>>print((datetime.now() - dateparser.parse('365 days', settings={'RELATIVE_BASE': datetime.now() - timedelta(seconds=1)})).days)
365
>>>print((datetime.now() - dateparser.parse('1 year', settings={'RELATIVE_BASE': datetime.now() - timedelta(seconds=1)})).days)
366
```
It seems to me that the root cause of the complexity/problem is that when parsing a time delta string, dateparser.parse returns a datetime object, rather than a datetime.timedelta object.

Thank you for the great package. It has helped me tremendously, already.

Operating System: Windows 10

**Comment by noviluni** [comment]
Hey @dshefman1!  Thank you for the feedback!

`dateparser.parse('365 days')` doesn't returns "364 days", it returns "the datetime for 365 days ago". However, when you are doing: `datetime.now() - dateparser.parse('365 days')`, the first expression ("now") is calculated a fraction of a second before the second expression, so when you substract them, there is a small difference. Let's illustrate it:

```python
>>> d = datetime.now() - dateparser.parse('365 days')
>>> d.days
364
>>> d.seconds/3600  # hours
23.99972222222222
```
So, as you can see, the difference is *almost* 365 days (354 days + 23.999 hours).

To handle this, I made a proposal (https://github.com/scrapinghub/dateparser/pull/623) for a new function called `parse_timedelta()` (which is not finished), but I didn't receive any feedback. You can see here the difference:

```python
>>> str(datetime.now()-parse('13 min ago'))
'0:12:59.993999'
>>> str(parse_timedelta('13 min ago'))
'0:13:00.000139'

>>> str(datetime.now()-parse('yesterday'))
'23:59:59.997510'
>>> str(parse_timedelta('yesterday'))
'1 day, 0:00:00.000182'
```
The idea would be to improve that function to round the microseconds to get a cleaner result.


If you want this feature, please, comment here or in the PR, and I would try to find a moment to work on it. In the meanwhile, if you need a solution, you could do something like this, where we round the seconds:

```python
>>> seconds = (datetime.now() - dateparser.parse('365 days')).total_seconds()
>>> timedelta(seconds=round(seconds, -1)).days
365
```

Let me know what you think :slightly_smiling_face:

**Comment by dshefman1** [comment]
Hi @noviluni Thank you for the assistance. 

Is there an elegant/simple way to use dateparser to create the result in days: `parse_func('365 days') == parse_func('1 year')`

When I use your solution below, with '1 year' I get 366, which is undesirable for my usecase:

```
>>> seconds = (datetime.now() - dateparser.parse('1 year')).total_seconds()
>>> print(timedelta(seconds=round(seconds, -1)).days)
366
```

**Comment by noviluni** [comment]
Hey @dshefman1!

It's returning 366 days because the current year is a **leap year** (February had 29 days), so when you use "1 year" it takes **"1 year ago" that was exactly 366 days ago**. If you run the same the next year you will get 365 days.

You can't do "365 days == 1 year" directly because it depends on the year.

If this is not what you expected you should search for another workaround. It's hard for me to give you an alternative without knowing the context.

You can inverse the operation if you specify in the settings that you want a date in the **future**, for example:

```python
>>> seconds = (dateparser.parse('1 year', settings={'PREFER_DATES_FROM': 'future'}) - datetime.now()).total_seconds()    
>>> timedelta(seconds=round(seconds, -1)).days                             
365
```
but of course, this will fail in 2023, as it will use again a leap year (2024) to calculate it. 

You could also use a **fixed date** from a non-leap year + a relative_base:

```python
>>> seconds = (datetime(2019, 1, 1) - dateparser.parse('1 year', settings={'RELATIVE_BASE': datetime(2019, 1, 1)})).total_seconds()
>>> timedelta(seconds=round(seconds, -1)).days                             
365
```

In this way, you will receive always 365, however, if you use "4 years" or more, you will receive the day for the leap year (Example: when using "4 years" it will return 1461 instead of 1460 (365*4)).

Let me know if any of these workarounds work for you.

**Comment by dshefman1** [comment]
Yes. Both of these solutions worked for me. Thank you.
