### ISSUE TITLE
Query for 1year future is giving wrong results 

### ISSUE THREAD

**Issue by shauryauppal** [scrapinghub/dateparser#810]
![Screenshot 2020-10-13 at 7 50 08 PM](https://user-images.githubusercontent.com/20338789/95873339-7508e880-0d8d-11eb-8ebb-e1b904121a04.png)
 
One year future query is giving output of 2019. We are in 2020.

**Comment by noviluni** [comment]
Hi @shauryauppal , which version of dateparser are you using? I tried with `dateparser==0.7.6` and it works:

```
>>> import dateparser

>>> dateparser.parse('tomorrow')
datetime.datetime(2020, 10, 28, 15, 14, 49, 431268)

>>> dateparser.parse('yesterday')
datetime.datetime(2020, 10, 26, 15, 15, 2, 326768)

>>> dateparser.parse('1484823450')
datetime.datetime(2017, 1, 19, 11, 57, 30)

>>> dateparser.parse('1 year', settings={'PREFER_DATES_FROM': 'future'})
datetime.datetime(2021, 10, 27, 15, 15, 47, 856920)
```

**Comment by shauryauppal** [comment]
dateparser==0.7.0

Installed by pip 14days ago

**Comment by noviluni** [comment]
Hi @shauryauppal , thanks for sharing.

That version was released 2 years and 8 months ago and the issue you mention is already fixed in the last versions.

You can try updating the `dateparser` version by doing: `pip install --no-cache-dir --upgrade`. If this doesn't work maybe it's an issue with your pip package and you can try updating it with: `python3 -m pip install --upgrade pip`.

I will close this issue as it's not a library bug. Feel free to comment if it didn't work.
