### ISSUE TITLE
ddmmyy regression in 1.0.0 version

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/dateparser#861]
in 0.7.6 all works:
```
>>> from dateparser import parse
>>> parse("100120")
datetime.datetime(2020, 10, 1, 0, 0)

```
however in 1.0.0 it's none

**Comment by noviluni** [comment]
Hi @manycoding,

This breaking change is documented in the changelog (https://github.com/scrapinghub/dateparser/releases/tag/v1.0.0). The `no-spaces-time` parser was disabled by default because it was generating false positives and a lot of results weren't intuitive.

You can recover the old behavior by using the `PARSERS` setting:
```python
# dateparser 1.0.0
>>> from dateparser import parse
>>> from dateparser_data.settings import default_parsers
>>> parse("100120",  settings={'PARSERS': default_parsers + ['no-spaces-time']})
datetime.datetime(2020, 10, 1, 0, 0)
```
I will close this issue, feel free to comment or reopen it if you have any other doubt.

Cheers!
