### ISSUE TITLE
Unexpected parse resolution

### ISSUE THREAD

**Issue by SameerSawla** [scrapinghub/dateparser#873]
```
import dateparser

to_parse = '20210126231003'
parsed = dateparser.parse(to_parse, date_formats=['%Y%m%d%H%M%s'])

print(to_parse)
print(parsed)
```
I am expecting it to resolve to Jan 26 2021... but it instead resolved to some date in 2034.

```
20210126231003
2034-01-16 03:23:43
```
I am curious on why this is happening. Is my understanding for the parser's functioning wrong?

**Comment by noviluni** [comment]
Hi @SameerSawla 

There's an error in your expression. As you can see [in the Python docs](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes), the sign for seconds (zero-padded) is `%S` (upper case) instead of `%s`.

```python
to_parse = '20210126231003'
>>> dateparser.parse(to_parse, date_formats=['%Y%m%d%H%M%S'])
datetime.datetime(2021, 1, 26, 23, 10, 3)
```

I will close the issue. Let me know if it doesn't work for you :)
