### ISSUE TITLE
cannot parse the date "20210202"

### ISSUE THREAD

**Issue by HazyGuo** [scrapinghub/dateparser#874]
dateparser.parse("20210202") returned None.

**Comment by noviluni** [comment]
Hi @HazyGuo 

You can use the `date_formats` parameter to add new date formats:

```python
>>> dateparser.parse("20210202", date_formats=['%Y%m%d'])
datetime.datetime(2021, 2, 2, 0, 0)
```

There's also a no-spaces-time parser (disabled by default) that you can use like this:

>>> dateparser.parse("20210202", settings={'PARSERS': ['no-spaces-time']})
datetime.datetime(1020, 2, 2, 2, 0)

However, the result probably doesn't work for you.

I will close this issue. Let me know if this doesn't work for you :)

**Comment by HazyGuo** [comment]
Thanks for your reply, but what I expect is to be able to parse various types of dates through one method, instead of giving different parameters for different date formats, I cannot predict the date format that needs to be parsed.
for example:
20200202
2020年2月2日
2020-02-02
2020-02-02 12:00:00
2020/02/02
2020年2月2日 12时整
...

**Comment by noviluni** [comment]
Hi @HazyGuo, as you can see in the next example, `date_formats` is to add support for those formats not supported, but it also works with other formats:

```python
dates = ["20200202", "2020年2月2日", "2020-02-02", "2020-02-02 12:00:00", "2020/02/02", "2020年2月2日 12时整"]

>>> for date in dates:
>>>    print(dateparser.parse(date))
None
2020-02-02 00:00:00
2020-02-02 00:00:00
2020-02-02 12:00:00
2020-02-02 00:00:00
None
```

```python
>>> for date in dates:
>>>     print(dateparser.parse(date, date_formats=['%Y%m%d']))
2020-02-02 00:00:00
2020-02-02 00:00:00
2020-02-02 00:00:00
2020-02-02 12:00:00
2020-02-02 00:00:00
None
```

This is because `20200202` could be `2020-02-02` but it also could be `2020-02-20 2:00` (20-20-02-02), etc. As the `dateparser` can't guess it you need to add the format. The last format is not supported yet, but you can also add it with `date_formats`.

Cheers
