### ISSUE TITLE
dateparser==0.7.6 using wrong tzlocal version

### ISSUE THREAD

**Issue by sirloon** [scrapinghub/dateparser#967]
Hi, I know 0.7.6 is deprecated with new 1.0 version, but I found out this requirement isn't specific enough:

https://github.com/scrapinghub/dateparser/blob/c5f0fa4707ccc5307359ad3f5be5f2ddb3eb304c/setup.py#L29

dateparser works with tzlocal 2.1, but it recently started to use tzlocal 3.x, which is incompatible: get_localzone() returns (eg. for UTC timezone):
- pytz.UTC in 2.1,
- datetime.timezone in 3.x.

dateparser is looking for a localize() method, only available in pytz.UTC

```
# tzlocal 2.1
> import tzlocal.unix
> type(tzlocal.unix._get_localzone())
pytz.UTC
```

```
# tzlocal 3.0
> import tzlocal.unix
> type(tzlocal.unix._get_localzone())
datetime.timezone
```

It might safer to better specify the version, even for 1.0+ releases.

**Comment by noviluni** [comment]
Hi @sirlon, thank you for opening this issue.

This is fixed in the last version (`dateparser` 1.0.0) and we can't modify old versions, so to get this working again you can either upgrade to the new `dateparser` version (that includes a lot of improvements vs the older versions, but doesn't support Python <= 3.5) or pin `tzlocal<=3.0`. Check this: https://github.com/scrapinghub/dateparser/issues/964

> It might safer to better specify the version, even for 1.0+ releases.
 
Pinning versions is not a good practice for those packages that will be dependencies of other projects (especially Open Source projects). Doing that can cause some bad consequences:
• if different dependencies pin different values for the requirements you won't be able to install them together
• if the dependence limits the maximum version of a requirement, you will require to keep an unupdated/unsecure version of that requirement and won't be able to update.

It is the project using the dependence (your project) where you can pin specific versions if that works better.

If we detect that a specific version or range of versions are breaking `dateparser` we can exclude them, that was what happened with regex, for example: https://github.com/scrapinghub/dateparser/issues/597

However, in case of `tzlocal` we decided to add support for both versions, so it is working with all versions and we don't need to specify anything in the requirements (https://github.com/scrapinghub/dateparser/pull/792).


I hope this will clarify your doubts. In case you have any other doubt you can answer or reopen this issue. And of course, if you find some versions of the dependencies that are not compatible with the last version 1.0.0 let me know and we will try to fix it :)

Cheers!

------------
Examples of other famous python libraries requirements:
* https://github.com/django/django/blob/main/setup.cfg#L39
* https://github.com/pytest-dev/pytest/blob/main/setup.cfg#L44
* https://github.com/ipython/ipython/blob/master/setup.py#L193
* https://github.com/pallets/flask/blob/main/setup.py#L6
