### ISSUE TITLE
REQUIRE_PARTS settings doesn't work as the example in the documentation

### ISSUE THREAD

**Issue by tiretfa** [scrapinghub/dateparser#969]
The documentation on https://dateparser.readthedocs.io/en/latest/settings.html#handling-incomplete-dates shows : 
```
>>> parse('2012', settings={'REQUIRE_PARTS': ['month']})
None
```
I tested it on my computer and that make : 
```
>>> from dateparser import parse
>>> parse('2012', settings={'REQUIRE_PARTS': ['month']})
datetime.datetime(2020, 1, 2, 0, 0)
```

My computer is MacOs Catalina 10.15.7 python version is Python 3.7.10 and the version of dateparser is dateparser==0.7.6.

**Comment by noviluni** [comment]
Hi @tiretfa, thank you for opening the issue. 

This was fixed in `dateparser=1.0.0` (here: https://github.com/scrapinghub/dateparser/pull/786). This happens because it's wrongly recognizing the `2012` as a date without spaces. 

As you know may guess, the old version is not supported anymore and we can't fix it, so I will close this issue. 

Thanks :)
