### ISSUE TITLE
Parser don't match certain formats

### ISSUE THREAD

**Issue by bokstaller** [scrapinghub/dateparser#994]
I tried to use date_formats to only use certain formats like 16.08.1988 and exclude things like 08/16/88 but it is somehow not working. Is there another method/attribute I can use to specify which things the parser should recognize and what not?

Thanks in advance!

**Comment by Gallaecio** [comment]
Could you provide some specific code examples (`>>>` lines) so that we can use them when fixing the issue to validate the fix?

**Comment by bokstaller** [comment]
Sure, I am using the most recent version of DateParser

```
import dateparser
dateparser.parse('4/11', languages=['de'], date_formats=["%A"])
>>>datetime.datetime(2021, 11, 4, 0, 0)
```

**Comment by Gallaecio** [comment]
That’s not exactly how `date_formats` works.

Dateparser has multiple internal parsers. You can change their order of application and disable some using the `PARSERS` setting. See https://dateparser.readthedocs.io/en/latest/settings.html?highlight=PARSERS#other-settings.

One of those parsers, `custom-formats`, attempts to parse the input using the values passed through the `date_formats` parameter.

If that does not result in a valid date being extracted (as it would not in your case, since `%A` expects things like “Monday”), Dateparser goes on to use another parser, which successfully interprets the input as Nov 4th.

What was your expected output here, passing `%A`?

**Comment by bokstaller** [comment]
Thanks for the explanation. My intention is to disable the parsing of dates like "4/11", so that the parser doesn't return a valid dateobject. Is this somehow possible?

**Comment by Gallaecio** [comment]
That depends on what dates you do want to support. You can disable parsers through the `PARSER` setting. But you may be disabling more than you want.

It is still not clear to me what input you _do_ want dateparser to support here. Could you give an example of a date that you _do_ want to get parsed, in the same scenario where `4/11` should return `None`?

**Comment by bokstaller** [comment]
I only want to parse complete dates like 4/11/2020 but not partial dates like 4/11 because I am in a setting where 4/11 means something else and would be parsed wrongly.

**Comment by Gallaecio** [comment]
See if anything in https://dateparser.readthedocs.io/en/latest/settings.html#handling-incomplete-dates helps.

**Comment by noviluni** [comment]
Hey @bokstaller, what about this?:

```python3
dateparser.parse('4/11', settings={'REQUIRE_PARTS': ['day', 'month', 'year']})
```

`REQUIRE_PARTS` allows to define if you require any "part" ("day", "month" and "year") or multiple.


I will close the issue as I think that my answer allows you to get what you want. Feel free to comment again or reopen the ticket in case it doesn't work for you. 

Cheers!
